Update context file URL
w3c-ccg/vc-status-list-2021 pull request #22
Opened 2022-03-11 14:50 UTC by clehner

Address #21

2022-03-11 15:13 UTC, msporny requested changes

2022-03-11 15:13 UTC, msporny commented on index.html
> +    "https://w3id.org/vc/status-list/v1"
I think we're going to have to go back to date-stamped values here... see https://github.com/w3c-ccg/vc-status-list-2021/issues/3#issuecomment-1062428949

2022-03-12 19:36 UTC, msporny commented on index.html
> +    "https://w3id.org/vc/status-list/v1"
Alright, done in https://github.com/w3c-ccg/vc-status-list-2021/pull/24 -- let me know what you think, @clehner.

2022-03-17 18:27 UTC, OR13 requested changes
Fix context links for close PR.

2022-03-17 18:32 UTC, msporny commented
> https://w3id.org/vc/status-list/v1

The correct (and only) URL is now: https://w3id.org/vc/status-list/2021/v1 ... but spec is waiting for PR #24 to be merged to make that correction.

@clehner -- we should probably close this PR, leaving it open is going to confuse people. This PR is now superseded by PR #24.

2022-03-17 19:10 UTC, OR13 commented
Closing, reopen if you disagree.

2022-03-17 19:10 UTC, closed without merging