Per issue #29 - Adding "id" field to credentialStatus in example
w3c-ccg/vc-status-list-2021 pull request #30
Opened 2022-06-10 19:48 UTC by yanicakj

Referencing this issue: https://github.com/w3c-ccg/vc-status-list-2021/issues/29

The example was a little misleading with the missing "id" field, adding it with this change.

2022-06-13 16:39 UTC, OR13 approved these changes

2022-06-13 16:58 UTC, msporny requested changes
The entry is a bit value in the list, so the suggested correction here is not correct. I've suggested changes here to something that might make a bit more sense.

2022-06-13 17:00 UTC, msporny commented on index.html
> +    "id": "https://example.com/status/3#list"
Hmm, thinking more about this... I remember @dlongley and I had a conversation a while ago about the `id` value here and decided to not put one, but can't remember all of the arguments against... or if I'm just imagining that conversation at this point.

2022-06-13 19:50 UTC, yanicakj commented on index.html
> +    "id": "https://example.com/status/3#list"
thanks for the correction 👍

2022-06-14 15:50 UTC, msporny approved these changes
LGTM.

2022-06-14 15:53 UTC, OR13 approved these changes

2022-06-14 15:54 UTC, dlongley approved these changes

2022-06-16 17:10 UTC, yanicakj commented
Hey all, I'm unable to merge this change after approvals, is there any additional steps needed? Not sure how it works - if PRs are merged on weekly/monthly basis by your team

2022-06-16 17:15 UTC, msporny commented
> Hey all, I'm unable to merge this change after approvals, is there any additional steps needed? Not sure how it works - if PRs are merged on weekly/monthly basis by your team

PRs are merged by Editors after enough review. This one has had enough review at this point, so I'll merge it down now.

If you'd like to become an Editor, please let us know and we can show you the ropes of what it takes to be an Editor of a specification.

2022-06-16 17:16 UTC, merged